<BottomBar2>:
    md_bg_color: '#394F8A'
    radius: 10
    MDRectangleFlatButton:
        pos_hint: {'right': (1354+64)/1440, 'center_y': 0.5}
        size_hint: 232/1440, 64/143
        md_bg_color: '#D9D9D9'
        text: "Reset"
        theme_text_color: "Custom"
        text_color: "black"
        line_color: "#B8ADAD"
        line_width: 3
        font_size: '32dp'
        valign: 'center'
        halign: 'center'
        on_press: root.reseter()

