<ScreenUtama>:
    MDFloatLayout:
        KartuPlaylist:
            pos_hint: {'center_x': (66+(621/2))/1440, 'center_y': (186+(600/2))/960}
            size_hint: 621/1440, 600/960
        KartuMonitor:
            pos_hint: {'center_x': (753+(621/2))/1440, 'center_y': (186+(600/2))/960}
            size_hint: 621/1440, 600/960
        BottomBar:
            pos_hint: {'center_x': 0.5, 'y': 0}
            size_hint: 1, 143/960
                